/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang3.RandomStringUtils;

import java.util.List;
import java.util.Random;
import java.util.ArrayList;

public class StringResourceHandlerTest {
  static Random rand = new Random();

  @Test public void testDefaultLocale() {
    List<Object> objs = new ArrayList<Object>();
    objs.add(String.valueOf(RandomStringUtils.random(rand.nextInt(100) + 1)));
    objs.add(Integer.valueOf(rand.nextInt()));
    objs.add(Double.valueOf(rand.nextDouble()));
    
    var msg = StringResourceHandler.getString("Test", objs);
    assertTrue("message format is incorrect", msg.contains("This is a test message"));

    for (Object obj : objs) {
      assertTrue(String.format("message %s does not contain expected argument %s", msg, obj.toString()), msg.contains(obj.toString()));
    }
  }
}
