/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.rpn;

import org.junit.Test;
import static org.junit.Assert.*;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import org.junit.After;
import org.junit.Before;

public class AppTest {

    private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
    private final PrintStream out = System.out;

    @Before
    public void setUp() {
      System.setOut(new PrintStream(outContent));
    }
  
    @After
    public void tearDown() {
      System.setOut(out);
    }
  
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should not be null", classUnderTest);
    }
}
