/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.rpn;

import java.util.Scanner;

import demo.calculator.RpnCalculator;

public class App {
    private static RpnCalculator rpnCalculator = new RpnCalculator();
    private static Scanner scanner = new Scanner(System.in);

    public static void main(String[] args) {
        while (true) {
            System.out.println("Please input commands.");
            String input = scanner.nextLine();
            if (input.equals("quit")) {
                return;
            }
            rpnCalculator.process(input);
        }
    }
}
